version: "2"

services:
  workspace:
    container_name: dockerhero_workspace
    image: johanvanhelden/dockerhero-workspace:php7.4
    volumes:
      - ./crons:/var/crons
      - ./databases:/var/www/databases
      - ./.phpmyadmin:/var/www/phpmyadmin
      - ./.phpredisadmin:/var/www/phpredisadmin
      - ./../:/var/www/projects
      - /etc/localtime:/etc/localtime:ro
    tty: true
    dns: 8.8.8.8
    networks:
      dockerhero:
        ipv4_address: 172.25.0.10

  php:
    container_name: dockerhero_php
    image: johanvanhelden/dockerhero-php-7.4-fpm:latest
    links:
      - db
      - workspace
      - redis
    volumes_from:
      - workspace
    volumes:
      - /etc/localtime:/etc/localtime:ro
    dns: 8.8.8.8
    ports:
      - "9912:9912"
    expose:
      - "9005"
    networks:
      dockerhero:
        ipv4_address: 172.25.0.11

  web:
    container_name: dockerhero_web
    image: johanvanhelden/dockerhero-nginx:latest
    links:
      - php
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/dockerhero/custom
      - nginx_logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - php
      - workspace
    ports:
      - "80:80"
      - "443:443"
    dns: 8.8.8.8
    networks:
      dockerhero:
        ipv4_address: 172.25.0.12

  db:
    container_name: dockerhero_db
    image: mysql:5.7
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - "database:/var/lib/mysql"
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dockerhero
      MYSQL_DATABASE: dockerhero
      MYSQL_USER: dockerhero
      MYSQL_PASSWORD: dockerhero
    dns: 8.8.8.8
    networks:
      dockerhero:
        ipv4_address: 172.25.0.13

  mail:
    container_name: dockerhero_mail
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    dns: 8.8.8.8
    networks:
      dockerhero:
        ipv4_address: 172.25.0.14

  redis:
    container_name: dockerhero_redis
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      dockerhero:
        ipv4_address: 172.25.0.15

volumes:
  database:
    driver: "local"
  nginx_logs:
    driver: "local"
  redis:
    driver: "local"

networks:
  dockerhero:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
